requires 'Moose';
requires 'DBIx::Class::Schema';
requires 'DBD::SQLite';
requires 'SQL::Translator';
requires 'Digest::SHA';
requires 'Digest::MD5';
requires 'Class::Method::Modifiers';
requires 'DBIx::Class::InflateColumn::Boolean';
requires 'DBD::Pg';
